version: "3.4"
services:      
  wordle_front:
    build:
      dockerfile: Dockerfile
      context: .
    command: ["npm", "start", "--prefix", "wordle-front"]
    environment:
      # TODO: mirar como se cogen variables de entorno en js
      WORDLE_API: "http://wordle_back:8000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
networks:
  default:
    name: wordle
